# Syncer Configuration.

log-level = "info"

server-id = 101

meta = "./syncer.meta"
worker-count = 16
batch = 10

pprof-addr = ":10081"

##replicate-do-db priority over replicate-do-table if have same db name
##and we support regex expression , start with '~' declare use regex expression.
#
#replicate-do-db = ["~^b.*","s1"]
#[[replicate-do-table]]
#db-name ="test"
#tbl-name = "log"

#[[replicate-do-table]]
#db-name ="test"
#tbl-name = "~^a.*"

# skip prefix mathched sqls
# skip-sqls = ["^ALTER\\s+USER", "^CREATE\\s+USER"]


[from]
host = "127.0.0.1"
user = "root"
password = ""
port = 3306

[to]
host = "127.0.0.1"
user = "root"
password = ""
port = 4000